-- ============================================================
-- SQL SETUP UNTUK SUPABASE - ABSENSI KKN
-- Copy dan paste script ini ke SQL Editor di Dashboard Supabase
-- ============================================================

-- 1. Buat Tabel Anggota
CREATE TABLE IF NOT EXISTS public.kkn_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL
);

-- 2. Buat Tabel Absensi
CREATE TABLE IF NOT EXISTS public.kkn_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anggota_id BIGINT NOT NULL,
    nama TEXT NOT NULL,
    tanggal DATE NOT NULL,
    jam TIME NOT NULL,
    status TEXT NOT NULL DEFAULT 'Hadir',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_absen_per_hari UNIQUE (anggota_id, tanggal)
);

-- 3. Matikan RLS (Row Level Security) agar dapat di-select, insert, dan delete dari Web Vanilla JS
ALTER TABLE public.kkn_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.kkn_attendance DISABLE ROW LEVEL SECURITY;

-- 3b. Grant akses penuh ke role anon & authenticated (digunakan oleh Supabase API Key publik)
GRANT ALL ON public.kkn_members TO anon, authenticated, service_role;
GRANT ALL ON public.kkn_attendance TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 3c. Buat Kebijakan RLS (Jika RLS diaktifkan di Supabase Dashboard)
DROP POLICY IF EXISTS "Allow all for kkn_attendance" ON public.kkn_attendance;
CREATE POLICY "Allow all for kkn_attendance" ON public.kkn_attendance FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for kkn_members" ON public.kkn_members;
CREATE POLICY "Allow all for kkn_members" ON public.kkn_members FOR ALL USING (true) WITH CHECK (true);

-- 4. Masukkan Data Awal 19 Anggota KKN
INSERT INTO public.kkn_members (id, nama) VALUES
(1, 'Adrian Dhaniella'),
(2, 'Alfia Nisa Hutami'),
(3, 'Anggun Halimatul Qolbiyyah'),
(4, 'Bintang Juniati'),
(5, 'Diky Ardiyansyah'),
(6, 'Dinar Suro Ati'),
(7, 'Fachry Billhaqi Ilham'),
(8, 'Jarkasih Kamaliyah'),
(9, 'Meisya Lutfiyah Hanum'),
(10, 'Muhammad Rizky'),
(11, 'Muhammad Sahid Wahyudi'),
(12, 'Nesa Erlita'),
(13, 'Nur Alvia Putri Fauziah'),
(14, 'Raden Krisna'),
(15, 'Rifan Firmannudin'),
(16, 'Rifki Rachman Fahlevi'),
(17, 'Shelyn Fatikha Leddiasyahri'),
(18, 'Suci Melati'),
(19, 'Wildan Handanto')
ON CONFLICT (id) DO NOTHING;
